"""add allowed_radius_meters to locations

Revision ID: 23e1839a76d1
Revises: ba6b6156f1d1
Create Date: 2026-09-10 13:58:49.484208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e1839a76d1'
down_revision: Union[str, Sequence[str], None] = 'ba6b6156f1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('allowed_radius_meters', sa.Integer(), nullable=False, server_default=sa.text('100')))
    op.alter_column('locations', 'allowed_radius_meters', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'allowed_radius_meters')
    # ### end Alembic commands ###
