"""create attendances table

Revision ID: 88c386a52652
Revises: 7c081912226e
Create Date: 2026-09-02 10:41:05.011667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c386a52652'
down_revision: Union[str, Sequence[str], None] = '7c081912226e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('clock_in_time', sa.DateTime(), nullable=False),
    sa.Column('clock_in_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('clock_in_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('clock_out_time', sa.DateTime(), nullable=True),
    sa.Column('clock_out_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('clock_out_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_location_id'), 'attendance', ['location_id'], unique=False)
    op.create_index(op.f('ix_attendance_organization_id'), 'attendance', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_organization_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_location_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
