"""add registered_device_id to employees

Revision ID: c4c341c9acdc
Revises: 23e1839a76d1
Create Date: 2026-09-10 16:34:19.773647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c341c9acdc'
down_revision: Union[str, Sequence[str], None] = '23e1839a76d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('registered_device_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'registered_device_id')
    # ### end Alembic commands ###
